# -*- coding: utf-8 -*-
"""day12_data_visualization_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sw2VuftbvlRJAeq_x8xG2fe1dc-QmaEY
"""

#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#dataset
data = {
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "Math": [85, 72, 90, 65, 78, 88, 95, 70],
    "Science": [80, 75, 92, 60, 82, 85, 90, 68],
    "English": [78, 80, 88, 70, 75, 90, 94, 72],
    "Attendance": [95, 88, 97, 75, 85, 92, 98, 80]
}

df = pd.DataFrame(data)

df

#check the data
print("Number of rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns)

print("\nDataset information:")
df.info()

#bar chart
plt.figure(figsize=(8, 5))

plt.bar(df["Student"], df["Math"])

plt.title("Math Marks of Students")
plt.xlabel("Student")
plt.ylabel("Math Marks")

plt.show()

#line chart
plt.figure(figsize=(8, 5))

plt.plot(df["Student"], df["Science"], marker="o")

plt.title("Science Marks of Students")
plt.xlabel("Student")
plt.ylabel("Science Marks")

plt.show()

#comparsion of subjects
plt.figure(figsize=(10, 6))

plt.plot(df["Student"], df["Math"], marker="o", label="Math")
plt.plot(df["Student"], df["Science"], marker="o", label="Science")
plt.plot(df["Student"], df["English"], marker="o", label="English")

plt.title("Comparison of Student Performance")
plt.xlabel("Student")
plt.ylabel("Marks")

plt.legend()

plt.show()

#seaborn
plt.figure(figsize=(8, 5))

sns.barplot(x="Student", y="Math", data=df)

plt.title("Math Marks using Seaborn")
plt.xlabel("Student")
plt.ylabel("Math Marks")

plt.show()

#seaborn scatter plot
plt.figure(figsize=(8, 5))

sns.scatterplot(
    x="Attendance",
    y="Math",
    data=df
)

plt.title("Attendance vs Math Marks")
plt.xlabel("Attendance (%)")
plt.ylabel("Math Marks")

plt.show()

#correlation analysis
correlation = df[["Math", "Science", "English", "Attendance"]].corr()

correlation

plt.figure(figsize=(8, 5))

sns.heatmap(correlation, annot=True)

plt.title("Correlation Heatmap")

plt.show()

#highest and lowest performers
highest_math = df.loc[df["Math"].idxmax()]
lowest_math = df.loc[df["Math"].idxmin()]

print("Highest Math Score:")
print(highest_math)

print("\nLowest Math Score:")
print(lowest_math)

#subj avg
print("Average Math:", df["Math"].mean())
print("Average Science:", df["Science"].mean())
print("Average English:", df["English"].mean())