# -*- coding: utf-8 -*-
"""Day 10 - Data Visualization ,Pie Chart and Chart Customization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIODmZnQ3n1hweS5uJ5j-hVUbhaVeSzl
"""

#matplotlib
import matplotlib.pyplot as plt

#data
subjects = ["Python", "SQL", "NumPy", "Pandas", "Statistics"]
marks = [80, 75, 85, 90, 78]

print(subjects)
print(marks)

#pie chart
plt.pie(marks, labels=subjects)

plt.title("Marks Distribution")

plt.show()

#percentages
plt.pie(
    marks,
    labels=subjects,
    autopct="%1.1f%%"
)

plt.title("Marks Distribution")

plt.show()

#colors adding
colors = ["red", "blue", "green", "orange", "purple"]

plt.pie(
    marks,
    labels=subjects,
    colors=colors,
    autopct="%1.1f%%"
)

plt.title("Marks Distribution")

plt.show()

#highlight one slice
explode = [0, 0, 0, 0.1, 0]

plt.pie(
    marks,
    labels=subjects,
    colors=colors,
    explode=explode,
    autopct="%1.1f%%"
)

plt.title("Marks Distribution")

plt.show()

#add a shadow
plt.pie(
    marks,
    labels=subjects,
    colors=colors,
    explode=explode,
    autopct="%1.1f%%",
    shadow=True
)

plt.title("Marks Distribution")

plt.show()

#bar chart
plt.figure(figsize=(8, 5))

plt.bar(
    subjects,
    marks,
    color="skyblue"
)

plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.title("Student Marks by Subject")

plt.show()

#horizontal bar chart
plt.barh(subjects, marks, color="lightgreen")

plt.xlabel("Marks")
plt.ylabel("Subjects")
plt.title("Student Marks")

plt.show()

#grid
plt.figure(figsize=(8, 5))

plt.bar(subjects, marks, color="coral")

plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.title("Student Marks")

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.show()

#line chart
plt.figure(figsize=(8, 5))

plt.plot(
    subjects,
    marks,
    marker="o",
    color="blue",
    linewidth=2
)

plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.title("Student Marks Trend")

plt.grid(True, linestyle="--", alpha=0.5)

plt.show()

"""Chart Comparison:

1. A bar chart is useful for comparing values between different categories.
2. A pie chart is useful for showing proportions of a whole.
3. A line chart is useful for showing changes or trends.
4. The choice of chart depends on the type of data and the question we want to answer.

Day 10 Insights:

1. Pandas has the highest mark with 90.
2. SQL has the lowest mark with 75.
3. The pie chart shows the proportion of each subject's marks relative to the total.
4. The bar chart makes it easy to compare marks between subjects.
5. The line chart shows how the marks change from one subject to another.
"""

#data visualization
plt.figure(figsize=(9, 5))

bars = plt.bar(
    subjects,
    marks,
    color=["#4C78A8", "#F58518", "#54A24B", "#E45756", "#B279A2"]
)

plt.title("Student Performance by Subject", fontsize=16)
plt.xlabel("Subjects", fontsize=12)
plt.ylabel("Marks", fontsize=12)

plt.ylim(0, 100)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height + 1,
        str(height),
        ha="center"
    )

plt.grid(axis="y", linestyle="--", alpha=0.3)

plt.show()