# -*- coding: utf-8 -*-
"""day11_Datavisualization_Histogram_Scatter Plot and Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aOo0gxjCHFkI_plp4pcb9EFP8rVCVlp
"""

#matplotlib
import matplotlib.pyplot as plt

#create marks data
marks = [
    45, 50, 52, 55, 58,
    60, 62, 65, 67, 68,
    70, 72, 74, 75, 78,
    80, 82, 85, 88, 90,
    92, 95
]

print(marks)

#bar chart using matplotlib
import matplotlib.pyplot as plt

students = ["A", "B", "C", "D", "E"]
marks = [85, 72, 90, 65, 78]

plt.figure(figsize=(8, 5))

plt.bar(students, marks)

plt.title("Student Marks")
plt.xlabel("Students")
plt.ylabel("Marks")

plt.show()

#line chart
import matplotlib.pyplot as plt

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
sales = [120, 150, 180, 160, 210, 250]

plt.figure(figsize=(8, 5))

plt.plot(months, sales, marker="o")

plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.grid(True)
plt.show()

#compare two categories using line chart
import matplotlib.pyplot as plt

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

product_A = [100, 120, 140, 130, 160, 180]
product_B = [80, 110, 130, 150, 170, 200]

plt.figure(figsize=(9, 5))

plt.plot(months, product_A, marker="o", label="Product A")
plt.plot(months, product_B, marker="s", label="Product B")

plt.title("Product Sales Comparison")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.legend()
plt.grid(True)

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

marks = [45, 50, 55, 60, 62, 65, 68, 70, 72, 75, 78, 80, 85, 90, 95]

plt.figure(figsize=(8, 4))

sns.boxplot(x=marks)

plt.title("Distribution of Student Marks")
plt.xlabel("Marks")

plt.show()

#grouped bar chart
import pandas as pd
import matplotlib.pyplot as plt

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Math": [85, 72, 90, 65, 78],
    "Science": [80, 75, 92, 60, 82],
    "English": [78, 80, 88, 70, 75]
}

df = pd.DataFrame(data)

x = range(len(df))

plt.figure(figsize=(10, 6))

plt.bar([i - 0.25 for i in x], df["Math"], width=0.25, label="Math")
plt.bar(x, df["Science"], width=0.25, label="Science")
plt.bar([i + 0.25 for i in x], df["English"], width=0.25, label="English")

plt.xticks(x, df["Student"])

plt.title("Subject-wise Student Performance")
plt.xlabel("Students")
plt.ylabel("Marks")

plt.legend()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

data = {
    "Math": [85, 72, 90, 65, 78, 88, 95, 70],
    "Science": [80, 75, 92, 60, 82, 85, 90, 68],
    "English": [78, 80, 88, 70, 75, 90, 94, 72],
    "Attendance": [95, 88, 97, 75, 85, 92, 98, 80]
}

df = pd.DataFrame(data)

correlation = df.corr()

plt.figure(figsize=(8, 6))

sns.heatmap(correlation, annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap")

plt.show()

import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [85, 72, 90, 65, 78]
}

df = pd.DataFrame(data)

highest = df.loc[df["Marks"].idxmax()]
lowest = df.loc[df["Marks"].idxmin()]

print("Highest Scoring Student:")
print(highest)

print("\nLowest Scoring Student:")
print(lowest)