# -*- coding: utf-8 -*-
"""day9_data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrwgiteokZ2jLoVRMC-Yg7l7EE4JWSxr
"""

#matplotlib
import matplotlib.pyplot as plt

#sample data
subjects = ["Python", "SQL", "NumPy", "Pandas", "Statistics"]
marks = [80, 75, 85, 90, 78]

print(subjects)
print(marks)

#line chart
plt.plot(subjects, marks)

plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.title("Student Marks")

plt.show()

#bar chart
plt.bar(subjects, marks)

plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.title("Student Marks - Bar Chart")

plt.show()

#pie chart
plt.pie(marks, labels=subjects, autopct="%1.1f%%")

plt.title("Marks Distribution")

plt.show()

#histogram
plt.hist(marks, bins=5)

plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.title("Distribution of Marks")

plt.show()

#scatter plot
study_hours = [1, 2, 3, 4, 5, 6, 7, 8]
student_marks = [45, 50, 55, 60, 65, 72, 80, 88]

plt.scatter(study_hours, student_marks)

plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Study Hours vs Marks")

plt.show()

"""OBSERVATIONS:
1. Pandas has the highest marks in the given dataset.
2. SQL has the lowest marks among the five subjects.
3. The histogram shows the distribution of marks.
4. The scatter plot indicates a positive relationship between study hours and marks.
"""